VER=1

CONFDIR = /usr/share/simple-ducky

BINPROGS = \
	simple-ducky \
	ducky-update

FLAT = \
	encoder.jar

MISC = \
	misc/7za.exe \
	misc/ncat.exe \
	misc/plink.exe\
	misc/psexec.exe \
	misc/putty.exe \
	misc/vssown.vbs \


MISCDBD = \
	misc/dbd/aes.c \
	misc/dbd/aes.h \
	misc/dbd/dbd.c \
	misc/dbd/dbd.h \
	misc/dbd/doexec.c \
	misc/dbd/doexec_unix.h \
	misc/dbd/doexec_win32.h \
	misc/dbd/Makefile \
	misc/dbd/misc.h \
	misc/dbd/mktarball.sh \
	misc/dbd/pel.c \
	misc/dbd/pel.h \
	misc/dbd/readwrite.h \
	misc/dbd/sha1.c \
	misc/dbd/sha1.h \
	misc/dbd/socket_code.h

MISCDBDCONFCONF = \
	misc/dbd-conf/dbd_defaults.conf \
	misc/dbd-conf/dbd-install.txt \
	misc/dbd-conf/dbd_unix_bind.conf \
	misc/dbd-conf/dbd_unix_reverse.conf \
	misc/dbd-conf/dbd_win_bind.conf \
	misc/dbd-conf/dbd_win_reverse.conf \

MISCDBDBINARIES = \
	misc/dbd/binaries/dbd-aarch64 \
	misc/dbd/binaries/dbd-aarch64-static \
	misc/dbd/binaries/dbd-arm7-static-diet \
	misc/dbd/binaries/dbd-armv7 \
	misc/dbd/binaries/dbd-armv7-static \
	misc/dbd/binaries/dbdbg.exe \
	misc/dbd/binaries/dbdbg-stealth.exe \
	misc/dbd/binaries/dbd.exe \
	misc/dbd/binaries/dbd-linux32 \
	misc/dbd/binaries/dbd-linux32-static \
	misc/dbd/binaries/dbd-linux32-static-diet \
	misc/dbd/binaries/dbd-ppc64-static \
	misc/dbd/binaries/dbd-ppc64-static-diet

PAYLOADS = \
	payloads/autopwnlocaldnsVIS7nouac.conf \
	payloads/autopwnlocaldnsVIS7uac.conf \
	payloads/autopwnlocaldnsWIN8nouac.conf \
	payloads/autopwnlocaldnsWIN8uac.conf \
	payloads/linuxrev.conf \
	payloads/livehashVIS7nouac.conf \
	payloads/livehashVIS7uac.conf \
	payloads/livehashWIN8nouac.conf \
	payloads/livehashWIN8uac.conf \
	payloads/osxrev.conf \
	payloads/osxsingleuserrev.conf \
	payloads/persistenceVIS7nouac.conf \
	payloads/persistenceVIS7uac.conf \
	payloads/persistenceWIN8nouac.conf \
	payloads/persistenceWIN8uac.conf \
	payloads/powershellVIS7admnouac.conf \
	payloads/powershellVIS7admuac.conf \
	payloads/powershellVIS7.conf \
	payloads/powershellWIN8admnouac.conf \
	payloads/powershellWIN8admuac.conf \
	payloads/powershellWIN8.conf \
	payloads/proxyinthemiddleWIN8.conf \
	payloads/proxyinthemiddleXPVIS7.conf \
	payloads/setlocaldnsVIS7nouac.conf \
	payloads/setlocaldnsVIS7uac.conf \
	payloads/setlocaldnsWIN8nouac.conf \
	payloads/setlocaldnsWIN8uac.conf \
	payloads/vssownVIS7uac.conf \
	payloads/vssownWIN8uac.conf \
	payloads/wifiautoconnectVIS7nouac.conf \
	payloads/wifiautoconnectVIS7uac.conf \
	payloads/wifiautoconnectWIN8nouac.conf \
	payloads/wifiautoconnectWIN8uac.conf \
	payloads/wifibackdoorVIS7nouac.conf \
	payloads/wifibackdoorVIS7uac.conf \
	payloads/wifibackdoorWIN8nouac.conf \
	payloads/wifibackdoorWIN8uac.conf \
	payloads/wifunVIS7nouac.conf \
	payloads/wifunVIS7uac.conf \
	payloads/wifunWIN8nouac.conf \
	payloads/wifunWIN8uac.conf \
	payloads/windowsdbdVIS7nouac.conf \
	payloads/windowsdbdVIS7uac.conf \
	payloads/windowsdbdWIN8nouac.conf \
	payloads/windowsdbdWIN8uac.conf \
	payloads/windowsrevVIS7nouac.conf \
	payloads/windowsrevVIS7uac.conf \
	payloads/windowsrevW2KXP.conf \
	payloads/windowsrevWIN8nouac.conf \
	payloads/windowsrevWIN8uac.conf

PAYLOADSBUILDERMAINATTACK = \
	payloads/builder/main-attack/livehash.conf \
	payloads/builder/main-attack/localdns.conf \
	payloads/builder/main-attack/ncshell.conf \
	payloads/builder/main-attack/nodownloadshell.conf \
	payloads/builder/main-attack/pitmvis7.conf \
	payloads/builder/main-attack/pitmwin8.conf \
	payloads/builder/main-attack/powershellexec.conf \
	payloads/builder/main-attack/powershellsys.conf \
	payloads/builder/main-attack/wifiautoconnect.conf \
	payloads/builder/main-attack/wifibackdoor.conf \
	payloads/builder/main-attack/wificred.conf

PAYLOADSBUILDEROSSELECT = \
	payloads/builder/os-select/win7admnouac.conf \
	payloads/builder/os-select/win7admuac.conf \
	payloads/builder/os-select/win8admnouac.conf \
	payloads/builder/os-select/win8admuac.conf \
	payloads/builder/os-select/xpusrall.conf

PAYLOADSBUILDERPOSTATTACK = \
	payloads/builder/post-attack/clearlogs.conf \
	payloads/builder/post-attack/finish.conf \
	payloads/builder/post-attack/finishlock.conf

PAYLOADSBUILDERPREATTACK = \
	payloads/builder/pre-attack/admusradd.conf \
	payloads/builder/pre-attack/firewall.conf \
	payloads/builder/pre-attack/hidecmd.conf \
	payloads/builder/pre-attack/rdpenable.conf

RESOURCES = \
	resources/be.properties \
	resources/de.properties \
	resources/dk.properties \
	resources/es.properties \
	resources/fr.properties \
	resources/it.properties \
	resources/keyboard.properties \
	resources/no.properties \
	resources/pt.properties \
	resources/ru.properties \
	resources/sv.properties \
	resources/uk.properties \
	resources/us.properties

SRC = \
	src/Encoder.java


install:

	#install  dirs
	install -dm755 $(DESTDIR)/usr/bin
	install -dm755 $(DESTDIR)$(CONFDIR)
	install -dm755 $(DESTDIR)$(CONFDIR)/misc
	install -dm755 $(DESTDIR)$(CONFDIR)/misc/dbd
	install -dm755 $(DESTDIR)$(CONFDIR)/misc/dbd/binaries
	install -dm755 $(DESTDIR)$(CONFDIR)/misc/dbd/conf
	install -dm755 $(DESTDIR)$(CONFDIR)/misc/dbd-conf
	install -dm755 $(DESTDIR)$(CONFDIR)/payloads
	install -dm755 $(DESTDIR)$(CONFDIR)/payloads/builder
	install -dm755 $(DESTDIR)$(CONFDIR)/payloads/builder/main-attack
	install -dm755 $(DESTDIR)$(CONFDIR)/payloads/builder/os-select
	install -dm755 $(DESTDIR)$(CONFDIR)/payloads/builder/post-attack
	install -dm755 $(DESTDIR)$(CONFDIR)/payloads/builder/pre-attack
	install -dm755 $(DESTDIR)$(CONFDIR)/resources
	install -dm755 $(DESTDIR)$(CONFDIR)/src



	install -m755 $(BINPROGS) $(DESTDIR)/usr/bin
	install -m755 $(FLAT) $(DESTDIR)$(CONFDIR)
	install -m755 $(MISC) $(DESTDIR)$(CONFDIR)/misc
	install -m755 $(MISCDBD) $(DESTDIR)$(CONFDIR)/misc/dbd
	install -m755 $(MISCDBDBINARIES) $(DESTDIR)$(CONFDIR)/misc/dbd/binaries
	install -m755 $(MISCDBDCONFCONF) $(DESTDIR)$(CONFDIR)/misc/dbd-conf
	install -m755 $(PAYLOADS) $(DESTDIR)$(CONFDIR)/payloads
	install -m755 $(PAYLOADSBUILDERMAINATTACK) $(DESTDIR)$(CONFDIR)/payloads/builder/main-attack
	install -m755 $(PAYLOADSBUILDEROSSELECT) $(DESTDIR)$(CONFDIR)/payloads/builder/os-select
	install -m755 $(PAYLOADSBUILDERPOSTATTACK) $(DESTDIR)$(CONFDIR)/payloads/builder/post-attack
	install -m755 $(PAYLOADSBUILDERPREATTACK) $(DESTDIR)$(CONFDIR)/payloads/builder/pre-attack
	install -m755 $(RESOURCES) $(DESTDIR)$(CONFDIR)/resources
	install -m755 $(SRC) $(DESTDIR)$(CONFDIR)/src
	ln -sf $(DESTDIR)$(CONFDIR)/misc/dbd-conf/* $(DESTDIR)$(CONFDIR)/misc/dbd/conf/


uninstall:
	for f in $(BINPROGS); do $(RM) $(DESTDIR)/usr/bin/$$f; done
	rm -rf $(DESTDIR)$(CONFDIR)

.PHONY: install uninstall


